//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elevi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elevi()
        {
            this.Absentes = new HashSet<Absente>();
            this.Notes = new HashSet<Note>();
            this.RapoarteEvaluares = new HashSet<RapoarteEvaluare>();
        }
    
        public int ElevID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public System.DateTime Data_nasterii { get; set; }
        public string Adresa { get; set; }
        public string ClasaID { get; set; }
        public int ParinteID { get; set; }
        public int UtilizatorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absente> Absentes { get; set; }
        public virtual Clase Clase { get; set; }
        public virtual Parinti Parinti { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapoarteEvaluare> RapoarteEvaluares { get; set; }
    }
}
