//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntervaleOre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntervaleOre()
        {
            this.OrarClases = new HashSet<OrarClase>();
        }
    
        public int IntervalID { get; set; }
        public System.TimeSpan Ora_inceput { get; set; }
        public System.TimeSpan Ora_sfarsit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrarClase> OrarClases { get; set; }
    }
}
