//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaje
    {
        public int MesajID { get; set; }
        public System.DateTime DataTrimitere { get; set; }
        public string Continut { get; set; }
        public int ExpeditorID { get; set; }
        public int DestinatarID { get; set; }
        public bool EsteCitit { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        public virtual Utilizatori Utilizatori1 { get; set; }
    }
}
