//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NotaID { get; set; }
        public decimal Nota { get; set; }
        public System.DateTime DataNota { get; set; }
        public int ElevID { get; set; }
        public int PredareID { get; set; }
    
        public virtual Elevi Elevi { get; set; }
        public virtual Predare Predare { get; set; }
    }
}
