//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificari
    {
        public int NotificareID { get; set; }
        public System.DateTime Data_Notificare { get; set; }
        public string Mesaj { get; set; }
        public bool EsteCitita { get; set; }
        public int ParinteID { get; set; }
    
        public virtual Parinti Parinti { get; set; }
    }
}
