//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_School_CatalogEntities : DbContext
    {
        public Online_School_CatalogEntities()
            : base("name=Online_School_CatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absente> Absentes { get; set; }
        public virtual DbSet<Clase> Clases { get; set; }
        public virtual DbSet<Conturi> Conturis { get; set; }
        public virtual DbSet<Elevi> Elevis { get; set; }
        public virtual DbSet<IntervaleOre> IntervaleOres { get; set; }
        public virtual DbSet<Materii> Materiis { get; set; }
        public virtual DbSet<Mesaje> Mesajes { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Notificari> Notificaris { get; set; }
        public virtual DbSet<OrarClase> OrarClases { get; set; }
        public virtual DbSet<Parinti> Parintis { get; set; }
        public virtual DbSet<Predare> Predares { get; set; }
        public virtual DbSet<Profesori> Profesoris { get; set; }
        public virtual DbSet<RapoarteEvaluare> RapoarteEvaluares { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Utilizatori> Utilizatoris { get; set; }
    }
}
