//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrarClase
    {
        public string ClasaID { get; set; }
        public string Zi_saptamana { get; set; }
        public int IntervalID { get; set; }
        public int PredareID { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual IntervaleOre IntervaleOre { get; set; }
        public virtual Predare Predare { get; set; }
    }
}
