//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parinti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parinti()
        {
            this.Elevis = new HashSet<Elevi>();
            this.Notificaris = new HashSet<Notificari>();
        }
    
        public int ParinteID { get; set; }
        public string Nume_parinte { get; set; }
        public string Prenume_parinte { get; set; }
        public string Numar_telefon { get; set; }
        public int UtilizatorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elevi> Elevis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificari> Notificaris { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
