//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogScolarOnline.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapoarteEvaluare
    {
        public int RaportID { get; set; }
        public int ElevID { get; set; }
        public double MediaGenerala { get; set; }
        public int AbsenteMotivate { get; set; }
        public int AbsenteNemotivate { get; set; }
        public string Comportament { get; set; }
        public string Descriere { get; set; }
        public System.DateTime DataGenerare { get; set; }
    
        public virtual Elevi Elevi { get; set; }
    }
}
